### ISSUE TITLE
how to build & run

### ISSUE THREAD

**Issue by ProfessorStrawberry** [skatpgusskat/how-fast-you-are#4]
Sorry to bother you. I have no idea, how to build.

If I open the folder in Visual Studio, I can only see 1 solution and that is keyboardHook.sln inside keyboardHook. If I run it, I get a console application showing me what buttons I pressed.

I figured client and server might be electron apps. But `npm install` and `npm start` don't give me any help.

Is there anything I miss?

감사합니다

**Comment by skatpgusskat** [comment]
Is it ok to show you how to run this at tomorrow steam?

**Comment by ProfessorStrawberry** [comment]
oh yea, what time will you stream though?
I have to work until 3 am KST tommorow.
I could watch the VOD. 

Thanks alot. I love the combo counter in your stream.

**Comment by skatpgusskat** [comment]
What about 10 PM KST?

**Comment by ProfessorStrawberry** [comment]
between 11:40 and 12:25 PM is working for me. I appreciate your help and time you take for me

**Comment by skatpgusskat** [comment]
Great. then I will fit to you. My stream time is 8:30PM to 1AM. 

Actually I made that backend system but awesome effect is made by my viewer “BigfoodK”. 
I hope If you on live stream and could run thia project, than please say “Thank you for great UI, bigfoodk”-like thing. :D

**Comment by ProfessorStrawberry** [comment]
sure will do B-)

**Comment by skatpgusskat** [comment]
Check README.md!

**Comment by ProfessorStrawberry** [comment]
감사합니다 😎
